services:
  - type: web
    name: conservation-quiz-backend
    env: node
    plan: free
    dir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: conservation-quiz-frontend
    dir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://conservation-quiz-backend.onrender.com
      - key: PUBLIC_URL
        value: /

