services:
  - type: web
    name: conservation-quiz-backend
    env: node
    plan: free
    dir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

