services:
  - type: web
    name: conservation-quiz-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: conservation-quiz-frontend
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://conservation-quiz-backend.onrender.com
      - key: PUBLIC_URL
        value: /

